<?php

use CRM_Civiparoisse_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Civip_Liste_Participants_Evenement',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'match' => [
        'name'
      ],
      'values' => [
        'name' => 'Civip_Liste_Participants_Evenement',
        'label' => E::ts('Participants à un Evénement'),
        'form_values' => null,
        'mapping_id' => null,
        'search_custom_id' => null,
        'api_entity' => 'Participant',
        'api_params' => [
          'version' => 4,
          'select' => [
            'contact_id.sort_name',
            'event_id.title',
            'role_id:label',
            'status_id:label',
            'Participant_Contact_contact_id_01.phone_primary.phone',
            'Participant_Contact_contact_id_01.email_primary.email',
            'Participant_Contact_contact_id_01.address_primary.street_address',
            'Participant_Contact_contact_id_01.address_primary.postal_code',
            'Participant_Contact_contact_id_01.address_primary.city',
            'Participant_Contact_contact_id_01.age_years',
            'Participant_Contact_contact_id_01.birth_date',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'Contact AS Participant_Contact_contact_id_01',
              'INNER',
              [
                'contact_id',
                '=',
                'Participant_Contact_contact_id_01.id',
              ],
            ],
          ],
          'having' => [],
        ],
        'expires_date' => null,
        'description' => E::ts('Affichage des Participants à un événement'),
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Civip_Liste_Participants_Evenement_SearchDisplay_Civip_Liste_Participants_Evenement_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Civip_Liste_Participants_Evenement_Table',
        'label' => E::ts('Participants à un événement Table'),
        'saved_search_id.name' => 'Civip_Liste_Participants_Evenement',
        'type' => 'table',
        'settings' => [
          'description' => null,
          'sort' => [
            [
              'contact_id.sort_name',
              'ASC',
            ],
          ],
          'actions' => [
            'contact.103',
            'contact.mailing',
            'download',
            'export',
            'contact.2',
            'contact.3',
            'contact.16',
          ],
          'limit' => 50,
          'classes' => [
            'table',
            'table-striped',
            'table-bordered',
          ],
          'pager' => [
            'show_count' => false,
            'expose_limit' => true,
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_id.sort_name',
              'dataType' => 'String',
              'label' => E::ts('Nom et Prénom'),
              'sortable' => true,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'contact_id',
                'target' => '_blank',
              ],
              'title' => E::ts('Voir Contact'),
              'icons' => [
                [
                  'field' => 'Participant_Contact_contact_id_01.contact_type:icon',
                  'side' => 'left',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'event_id.title',
              'dataType' => 'String',
              'label' => E::ts('Nom de l\'événement'),
              'sortable' => true,
              'link' => [
                'path' => '',
                'entity' => 'Event',
                'action' => 'view',
                'join' => 'event_id',
                'target' => 'crm-popup',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'role_id:label',
              'dataType' => 'String',
              'label' => E::ts('Rôle'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Statut'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.email_primary.email',
              'dataType' => 'String',
              'label' => E::ts('Courriel'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.phone_primary.phone',
              'dataType' => 'String',
              'label' => E::ts('Téléphone portable'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.address_primary.street_address',
              'dataType' => 'String',
              'label' => E::ts('Adresse'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.address_primary.postal_code',
              'dataType' => 'String',
              'label' => E::ts('Code postal'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.address_primary.city',
              'dataType' => 'String',
              'label' => E::ts('Ville'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.age_years',
              'dataType' => 'Integer',
              'label' => E::ts('Âge (année)'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'Participant_Contact_contact_id_01.birth_date',
              'dataType' => 'Date',
              'label' => E::ts('Date de naissance'),
              'sortable' => true,
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Participant',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Mettre à jour un Participant'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'Participant',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Supprimer un Participant'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'Participant',
                  'action' => 'detach',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-random',
                  'text' => E::ts('Déplacer un Participant'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'placeholder' => 5,
          'actions_display_mode' => 'menu',
          'button' => 'Rechercher',
          'headerCount' => true,
          'noResultsText' => 'Sélectionner un ou des événements, et cliquer sur Rechercher',
          'toolbar' => [
            [
              'entity' => 'Participant',
              'action' => 'add',
              'join' => '',
              'target' => 'crm-popup',
              'icon' => 'fa-plus',
              'text' => E::ts('Ajouter un Participant'),
              'style' => 'primary',
              'path' => '',
              'task' => '',
              'condition' => [],
            ],
          ],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
];