<?php

use CRM_Civiparoisse_ExtensionUtil as E;

/**
 * action pour envoyer un mail aux parents
 * @see CRM_Mailing_Form_Task_AdhocMailing
 */
class CRM_Civiparoisse_Formulaires_Form_ParentMailingTask extends CRM_Contact_Form_Task
{
  /**
   * @inheritdoc
   * @see CRM_Mailing_Form_Task_AdhocMailing::preProcess
   * @return void
   * @throws CRM_Core_Exception
   * @throws \Civi\API\Exception\UnauthorizedException
   * @throws \Random\RandomException
   */
  public function preProcess()
  {
    //attention : ici parents et enfants sont pris au sens familial - pas au sens du chaînage informatique (listes liées)

    parent::preProcess(); // fait le travail commun aux actions sur un ensemble de contacts
    //groupId : l'id du groupe
    //ssId : l'id du saved search : il y en a un si et seulement si le groupe est dynamique
    list ($childGroupId, $childSsId) = $this->createHiddenGroup(); //on sauvegarde le groupe représentant les contacts

    if (!is_null($childSsId)) {
      //le refresh invalide et recharge le cache
      \Civi\Api4\Group::refresh(true)->addWhere('id', '=', $childGroupId)->execute();
      CRM_Core_Session::setStatus(E::ts('You used a dynamic group. Please note that the resulting group generated by the parent mailing action will still be static.'), E::ts('Dynamic group in children selection'));
    }
    $childrenIds = array_keys(CRM_Contact_BAO_Group::getMember($childGroupId));//requête valide pour les groupes statiques et dynamiques

    $parentIds = \Civi\Api4\Relationship::get(TRUE)
      ->addSelect('contact_id_b')
      ->addWhere('relationship_type_id:name', '=', 'Child of')
      ->addWhere('contact_id_a', 'IN', $childrenIds)
      ->setLimit(0)
      ->setOffset(0)
      ->execute()->column('contact_id_b');

    //créer le groupe pour les parents
    $randID = bin2hex(random_bytes(16));
    $grpTitle = "Hidden Group {$randID}";
    $grpID = CRM_Core_DAO::getFieldValue('CRM_Contact_DAO_Group', $grpTitle, 'id', 'title');

    if (!$grpID) {
      $groupParams = [
        'title' => $grpTitle,
        'is_active' => 1,
        'is_hidden' => 1,
        'group_type' => ['2' => 1],
      ];

      $parentGroup = CRM_Contact_BAO_Group::writeRecord($groupParams);
      $parentGroupId = $parentGroup->id;

      //ajout des contacts parents au groupe des parents
      CRM_Contact_BAO_GroupContact::addContactsToGroup($parentIds, $parentGroup->id);

      //renommage du groupe
      $newGroupTitle = "Hidden Group {$parentGroupId}";
      $groupParams = [
        'id' => $parentGroupId,
        'name' => CRM_Utils_String::titleToVar($newGroupTitle),
        'title' => $newGroupTitle,
        'group_type' => ['2' => 1],
      ];
      CRM_Contact_BAO_Group::writeRecord($groupParams);

      //et enfin, on déclenche le mailing

      $templateTypes = CRM_Mailing_BAO_Mailing::getTemplateTypes();


      $mailing = civicrm_api3('Mailing', 'create', [
        'name' => "",
        'campaign_id' => NULL,
        'replyto_email' => "",
        'template_type' => $templateTypes[0]['name'],
        'template_options' => ['nonce' => 1],
        'subject' => "",
        'body_html' => "",
        'body_text' => "",
        'groups' => [
          'include' => [$parentGroupId],
          'exclude' => [],
          'base' => [],
        ],
        'mailings' => [
          'include' => [],
          'exclude' => [],
        ],
      ]);

      CRM_Utils_System::redirect(CRM_Utils_System::url('civicrm/a/', NULL, TRUE, '/mailing/' . $mailing['id']));


    } else {
      //ne devrait normalement pas arriver, si la source d'aléa est correcte
      CRM_Core_Session::setStatus(E::ts('There was an error in group creation. Please try again'), E::ts('Group creation failure'), 'error');
    }
  }

}
